version: '3.2'
services: 
    blog_db: 
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Loc@04071999"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    blog_api: 
        build: .
        depends_on: 
          - blog_db
        environment: 
            ConnectionStrings__BlogDBConnection: "Server=blog_db; Database=BlogDB_API; User ID=sa; Password=Loc@04071999"
        ports:
            - "5000:80"
